=== AbdelhameedOsama/Attendance-management-system/xml/projectSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Define types for elements -->
	<xs:simpleType name="userIDType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[ATSC]\d{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3,} [a-zA-Z]{3,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--	<xs:simpleType name="passwordType">
		<xs:restriction base="xs:string">
			<xs:pattern value="^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&_;*()_+,-./:<=>?@[\]^_`{|}~])(?=.*[A-Z]).{8,}$"/>
		</xs:restriction>
	</xs:simpleType>-->
	<xs:simpleType name="passwordType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,})$"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Present"/>
			<xs:enumeration value="Absent"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Define elements -->
	<xs:element name="School">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Users" type="UsersType"/>
				<xs:element name="Class" type="ClassType" maxOccurs="unbounded"/>
				<xs:element name="AttendanceData" type="AttendanceDataType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="UsersType">
		<xs:sequence>
			<xs:element name="Admin" type="AdminType"/>
			<xs:element name="Teacher" type="TeacherType" maxOccurs="unbounded"/>
			<xs:element name="Student" type="StudentType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdminType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType"/>
			<xs:element name="Name" type="nameType"/>
			<xs:element name="Email" type="emailType"/>
			<xs:element name="Password" type="passwordType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TeacherType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType"/>
			<xs:element name="Name" type="nameType"/>
			<xs:element name="Email" type="emailType"/>
			<xs:element name="Password" type="passwordType"/>
		</xs:sequence>
		<xs:attribute name="Supervisor" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="StudentType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType"/>
			<xs:element name="Name" type="nameType"/>
			<xs:element name="Email" type="emailType"/>
			<xs:element name="Password" type="passwordType"/>
			<xs:element name="ClassName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ClassType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Supervisor">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="UserID" type="userIDType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Teachers" type="TeachersType"/>
			<xs:element name="Students" type="StudentsType" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TeachersType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StudentsType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttendanceDataType">
		<xs:sequence>
			<xs:element name="AttendanceRecord" type="AttendanceRecordType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AttendanceRecordType">
		<xs:sequence>
			<xs:element name="UserID" type="userIDType"/>
			<xs:element name="Date" type="xs:date"/>
			<xs:element name="Status" type="statusType"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AbdelhameedOsama/Attendance-management-system/xml/ProjectXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<School xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projectSchema.xsd">
  <Users>
    <Admin>
      <UserID>A001</UserID>
      <Name>John Doe</Name>
      <Email>Admin@admin.com</Email>
      <Password>123456789Aa</Password>
    </Admin>
    <Teacher Supervisor="false">
      <UserID>T101</UserID>
      <Name>ahmed ali</Name>
      <Email>ali@2gm.com</Email>
      <Password>123@ASDasa</Password>
    </Teacher>
    <Teacher Supervisor="true">
      <UserID>T001</UserID>
      <Name>Mohammed AbuTrika</Name>
      <Email>AbuTrika22@teacher.com</Email>
      <Password>AlAhly22@Trika</Password>
    </Teacher>
    <Teacher Supervisor="true">
      <UserID>T002</UserID>
      <Name>Nadin Saleh</Name>
      <Email>NadinSaleh@teacher.com</Email>
      <Password>@aad2daW</Password>
    </Teacher>
    <Teacher Supervisor="false">
      <UserID>T004</UserID>
      <Name>Amira Salah</Name>
      <Email>Amira@teacher.com</Email>
      <Password>Ac1515as</Password>
    </Teacher>
    <Student>
      <UserID>S001</UserID>
      <Name>Abdelhameed Osama</Name>
      <Email>abdelhameed_osama@example.com</Email>
      <Password>611</Password>
      <ClassName>PD</ClassName>
    </Student>
    <Student>
      <UserID>S002</UserID>
      <Name>AbdUllah Aiman</Name>
      <Email>abdUllah_aiman@example.com</Email>
      <Password>123456789Aa</Password>
      <ClassName>AI</ClassName>
    </Student>
    <Student>
      <UserID>S003</UserID>
      <Name>Omar Abdullah</Name>
      <Email>omar_abdullah@example.com</Email>
      <Password>123456789Aa</Password>
      <ClassName>OS</ClassName>
    </Student>
  </Users>
  <Class>
    <Name>PD</Name>
    <Supervisor>
      <UserID>T001</UserID>
    </Supervisor>
    <Teachers>
      <UserID>T001</UserID>
      <UserID>T002</UserID>
      <UserID>T004</UserID>
    </Teachers>
    <Students>
      <UserID>S001</UserID>
      <UserID>S002</UserID>
    </Students>
  </Class>
  <Class>
    <Name>OS</Name>
    <Supervisor>
      <UserID>T002</UserID>
    </Supervisor>
    <Teachers>
      <UserID>T101</UserID>
      <UserID>T001</UserID>
    </Teachers>
    <Students>
      <UserID>S003</UserID>
    </Students>
  </Class>
  <Class>
    <Name>AI</Name>
    <Supervisor>
      <UserID>T004</UserID>
    </Supervisor>
    <Teachers>
      <UserID>T001</UserID>
      <UserID>T002</UserID>
      <UserID>T004</UserID>
    </Teachers>
    <Students>
      <UserID>S002</UserID>
    </Students>
  </Class>
  <AttendanceData>
    <AttendanceRecord>
      <UserID>S001</UserID>
      <Date>2024-02-15</Date>
      <Status>Present</Status>
    </AttendanceRecord>
    <AttendanceRecord>
      <UserID>S002</UserID>
      <Date>2024-02-15</Date>
      <Status>Present</Status>
    </AttendanceRecord>
    <AttendanceRecord>
      <UserID>S002</UserID>
      <Date>2024-02-16</Date>
      <Status>Absent</Status>
    </AttendanceRecord>
    <AttendanceRecord>
      <UserID>S002</UserID>
      <Date>2024-02-17</Date>
      <Status>Present</Status>
    </AttendanceRecord>
    <AttendanceRecord>
      <UserID>S002</UserID>
      <Date>2024-02-18</Date>
      <Status>Absent</Status>
    </AttendanceRecord>
    <!-- Add more attendance records as needed -->
  </AttendanceData>
</School>

=== AbdelhameedOsama/Attendance-management-system/xml/ProjectSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<School xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projectSchema.xsd">
	<Users>
		<Admin>
			<UserID>A001</UserID>
			<Name>John Doe</Name>
			<Email>Admin@admin.com</Email>
			<Password>123456789Aa</Password>
		</Admin>
		<Teacher>
			<UserID>T001</UserID>
			<Name>Nadia Saleh</Name>
			<Email>NadiaSaleh@teacher.com</Email>
			<Password>123456789Aa</Password>
		</Teacher>
		<Teacher>
			<UserID>T002</UserID>
			<Name>Nadin Saleh</Name>
			<Email>NadinSaleh@teacher.com</Email>
			<Password>Ac1515as</Password>
		</Teacher>
		<Student>
			<UserID>S001</UserID>
			<Name>Abdelhameed Osama</Name>
			<Email>abdelhameed_osama@example.com</Email>
			<Password>611</Password>
			<ClassName>C001</ClassName>
		</Student>
		<Student>
			<UserID>S002</UserID>
			<Name>AbdUllah Aiman</Name>
			<Email>abdUllah_aiman@example.com</Email>
			<Password>123456789Aa</Password>
			<ClassName>C001</ClassName>
		</Student>
		<Student>
			<UserID>S003</UserID>
			<Name>Omar Abdullah</Name>
			<Email>omar_abdullah@example.com</Email>
			<Password>123456789Aa</Password>
			<ClassName>C001</ClassName>
		</Student>
	</Users>
	<Class>
		<Name>PD</Name>
		<Supervisor>
			<UserID>T001</UserID>
		</Supervisor>
		<Teachers>
			<UserID>T001</UserID>
			<UserID>T002</UserID>
		</Teachers>
		<Students>
			<UserID>S001</UserID>
			<UserID>S002</UserID>
			<UserID>S003</UserID>
		</Students>
	</Class>
	<AttendanceData>
		<AttendanceRecord>
			<UserID>S001</UserID>
			<Date>2024-02-15</Date>
			<Status>Present</Status>
		</AttendanceRecord>
		<AttendanceRecord>
			<UserID>S002</UserID>
			<Date>2024-02-15</Date>
			<Status>Absent</Status>
		</AttendanceRecord>
		<!-- Add more attendance records as needed -->
	</AttendanceData>
</School>
